### ISSUE TITLE
List of packages with gnulib problems

### ISSUE THREAD

**Issue by fede2cr** [fede2cr/slackware_riscv#2]
A number of packages are presenting this problem. It might be something with the Fedora stage4 o with riscv itself. Need to do more testing.

Here's an example with Bison.

  CC       lib/vasnprintf.o
lib/fseterr.c: In function 'fseterr':
lib/fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
   ^~~~~
make[2]: *** [Makefile:3461: lib/fseterr.o] Error 1

**Comment by fede2cr** [comment]
Another, coreutils.
  CC       lib/freadseek.o
lib/freadseek.c: In function 'freadptrinc':
lib/freadseek.c:68:3: error: #error "Please port gnulib freadseek.c to your platform! Look at the definition of getc, getc_unlocked on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadseek.c to your platform! Look at the definition of getc, getc_unlocked on your system, then report this to bug-gnulib."
   ^~~~~
make[2]: *** [Makefile:9134: lib/freadseek.o] Error 1

**Comment by fede2cr** [comment]
Finished compiling coreutils after adding patch coreutils-8.29-gnulib-fflush.patch.gz from Fedora SRPM.

Not adding findutils to the list.
freadahead.c: In function 'freadahead':
freadahead.c:64:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread on your system, then report this to bug-gnulib."
   ^~~~~

**Comment by fede2cr** [comment]
Adding m4 to the list.

make[3]: Entering directory '/tmp/m4-1.4.18/lib'
  CC       glthread/lock.o
  CC       freadahead.o
freadahead.c: In function 'freadahead':
freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[3]: *** [Makefile:1910: freadahead.o] Error 1

**Comment by fede2cr** [comment]
Adding gzip to the list. Already tried the Git version and I get similar error.

fseterr.c: In function 'fseterr':
fseterr.c:78:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
   ^~~~~
make[3]: *** [Makefile:1774: fseterr.o] Error 1
make[3]: *** Waiting for unfinished jobs....
fseeko.c: In function 'rpl_fseeko':
fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
    ^~~~~
make[3]: *** [Makefile:1774: fseeko.o] Error 1

**Comment by fede2cr** [comment]
Adding libunistring

gcc -DHAVE_CONFIG_H -DNO_XMALLOC -I. -I..  -I. -I. -I.. -I.. -DIN_LIBUNISTRING -DDEPENDS_ON_LIBICONV=1   -O2 -c fseterr.c
fseterr.c: In function 'fseterr':
fseterr.c:87:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
   ^~~~~
make[2]: *** [Makefile:5887: config.h] Error 1
make[2]: Leaving directory '/tmp/libunistring-0.9.9/lib'

**Comment by fede2cr** [comment]
Adding dc3dd.

gcc  -I.      -O2 -fPIC -MT freadahead.o -MD -MP -MF $depbase.Tpo -c -o freadahead.o freadahead.c &&\
mv -f $depbase.Tpo $depbase.Po
freadahead.c: In function 'freadahead':
freadahead.c:69:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[3]: *** [Makefile:1221: freadahead.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/tmp/dc3dd-7.2.646/lib'

**Comment by vrushali88** [comment]
Adding groff. 

Gives same error while trying to build using latest gcc8 on Fedora (Rawhide)

**Comment by fede2cr** [comment]
Actually groff is compiling properly, both on slackware-riscv64 as well as on the Fedora riscv stage4 with gcc 7.3.1. I'll be uploading my package shortly.
Slackware-current (any-arch) doesn't have gcc8 yet so I won't have this problem at this time.

**Comment by fede2cr** [comment]
Oh, actually, I've already uploaded the groff package 23 days ago.
Please let me know if there is any instability or use problems with the tool.

**Comment by fede2cr** [comment]
Adding sharutils

make[4]: Entering directory '/tmp/sharutils-4.15.2/lib'
gcc -DHAVE_CONFIG_H -I. -I..     -O2 -Wno-format-contains-nul -MT fseeko.o -MD -MP -MF .deps/fseeko.Tpo -c -o fseeko.o fseeko.c
fseeko.c: In function 'rpl_fseeko':
fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
    ^~~~~
make[4]: *** [Makefile:1610: fseeko.o] Error 1
make[4]: Leaving directory '/tmp/sharutils-4.15.2/lib'

**Comment by DannyThomas** [comment]
FWIW I had the "Please port gnulib fseeko.c to your platform!" when building m4 on Fedora29
I believe for m4 it happens because a new tarball has not been generated with a
fix for the gnulib included as lib/
http://www.linuxfromscratch.org/lfs/view/development/chapter06/m4.html
First, make some fixes required by glibc-2.28:
sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h

see also
https://bugzilla.redhat.com/show_bug.cgi?id=1595702
https://bugzilla.redhat.com/show_bug.cgi?id=1603751

**Comment by jorpilo** [comment]
I can confirm what @DannyThomas said http://www.linuxfromscratch.org/lfs/view/development/chapter06/m4.html

works for coreutils. Testing to compile Lava-M coreutils with the fix and it works

**Comment by guruthree** [comment]
> I can confirm what @DannyThomas said http://www.linuxfromscratch.org/lfs/view/development/chapter06/m4.html
> 
> works for coreutils. Testing to compile Lava-M coreutils with the fix and it works

Slightly off topic, but this fix works for Gentoo, thanks!

**Comment by fede2cr** [comment]
The rest of the package have been fixed, either by using patches from Slackware, upgrading to Slackware's version, or adding this fix.
